version: "3"
services:
  scd:
    #    image: sergioadsf/scd-batch:1.4
    build: .
    container_name: scd
    environment:
      - url_csv=/bck/
    volumes:
      - ./target/scd-0.0.1-SNAPSHOT.jar:/app.jar
      - /home/sergio/Downloads/files:/bck/
    ports:
      - "8082:8082"